"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { useState, useEffect } from "react";
import { UserProvider } from "@/contexts/userContext";
import { AuthProvider } from "@/contexts/authContext";
import { RotaPrivada, checarRotas } from "./rotasPrivadas";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

/* export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {
	const epublico = checarRotas(usePathname());

	return (
		<html lang="en">
			<body>
				<AuthProvider>
					<UserProvider>
						{epublico && children}
						{!epublico && <RotaPrivada>{children}</RotaPrivada>}
					</UserProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
